version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"   # ðŸ‘ˆ Exposed to VM public IP
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: appdb
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: khaledmohamedatia/myapi:latest
    container_name: dotnet_api
    restart: always
    ports:
      - "80:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=appdb;User=root;Password=root123;"
    depends_on:
      - db

volumes:
  mysql_data:
